name: 02 - Workflow Events

on: push

jobs:
    show-trigger:
        runs-on: ubuntu-latest
        steps: 
            - name: "Show the trigger"
              run: |
                echo "Event name: ${{ github.event_name }}"