name: 04 - Using Actions

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4 
            - name: Printing Folders
              run: ls 
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Install Dependencies
              working-directory: 04-using-actions/react-app
              run: npm ci